### ISSUE TITLE
AttributeError when __enter__ method returns tuple 

### ISSUE THREAD

**Issue by gb14** [gforcada/flake8-builtins#26]
After upgrading to 1.2.2 we are getting this error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/ve/lib/python3.6/site-packages/flake8/checker.py", line 648, in _run_checks
    return checker.run_checks()
  File "/ve/lib/python3.6/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/ve/lib/python3.6/site-packages/flake8/checker.py", line 493, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/ve/lib/python3.6/site-packages/flake8_builtins.py", line 103, in run
    for line, offset, msg, rtype in value:
  File "/ve/lib/python3.6/site-packages/flake8_builtins.py", line 192, in check_with
    if var and var.id in BUILTINS:
AttributeError: 'Tuple' object has no attribute 'id'
```
This is caused by something like:
```python
with my_manager() as (a, b):
  ....
```

**Comment by gforcada** [comment]
@gb14 thanks for using and reporting your errors with flake8-builtins!

I didn't think of a context manager that returns more than one object that gets unpacked on the with statement right away, sure Python can be creative at a times :smile: 

I will try to fix that as soon as possible, or would you be interested to try to tackle this issue?

To begin with a test case would be great :-)

**Comment by gforcada** [comment]
@gb14 flake8-builtins 1.2.3 is out! Please give it a try

**Comment by gb14** [comment]
Thank you :)
