### ISSUE TITLE
`AttributeError` seen with versions 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by tim-ireland** [gforcada/flake8-builtins#23]
With version flake8-builtins 1.2.0 and later I'm seeing the following issue while running `flake8`.  It works fine with flake8-builtins 1.1.1.

Using python 2.7.14

```python
[root@532b769a6003 /]# flake8 src/
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 317, in run
    self.run_parallel()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 286, in run_parallel
    for ret in pool_map:
  File "/opt/python/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/python/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by gforcada** [comment]
@tim-ireland thanks for using flake8-builtins and reporting the issues you find with it!!

I see on the traceback nothing directly related to flake8-builtins, but rather multiprocessing, would you mind trying to run the same flake8 command with ``-j 1`` as an extra argument? So turning off multiprocessing to see if we can get a clear traceback?

On the other hand, if you safely copy that ``src`` folder and keep deleting files and lines in files, can you get a minimal example that makes flake8-builtins fail with this traceback?

**Comment by tim-ireland** [comment]
@gforcada good call with `-j 1`.  Here's what I found:

```python
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8_builtins.py", line 103, in run
    for line, offset, msg, rtype in value:
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8_builtins.py", line 182, in check_with
    if var.id in BUILTINS:
AttributeError: 'Attribute' object has no attribute 'id'
```

Adding a `print var` just before line 182, I saw lots of `_ast.Name object`'s but it failed at the first `_ast.Attribute` object:

```python
<_ast.Name object at 0x7f4a2a6ce650>
<_ast.Attribute object at 0x7f4a2a86cbd0> 
```

Added the following exception handler:

```python
    180         if getattr(statement, 'optional_vars', None):
    181             var = statement.optional_vars
    182             try:
    183                 if var.id in BUILTINS:
    184                     yield (
    185                         statement.lineno,
    186                         statement.col_offset,
    187                         self.assign_msg.format(var.id),
    188                         type(self),
    189                     )
    190             except AttributeError as e:
    191                 print e
    192                 print ast.dump(var)
    193                 print var.value.id
```

With result:

```python
'Attribute' object has no attribute 'id'
Attribute(value=Name(id='self', ctx=Load()), attr='session', ctx=Store())
self
```

**Comment by gforcada** [comment]
@tim-ireland thanks for the quick answer, what would be interesting is to have a minimal code snippet hat allows us to reproduce the issue and encode it on a test so that we can ensure we can fix the code and that no future changes on the code regress on it. Would you mind providing that? I'm a bit puzzled over a with statement have an ``ast.Attribute``

**Comment by danpalmer** [comment]
@gforcada here's a minimal test case...

```python
for a, *bs in ():
    pass
```

I'll take a stab at a fix now.

**Comment by danpalmer** [comment]
I think I was seeing a slightly different error, it looks like this might be a bigger task, to implement handling for the other types of AST node that can appear in an assignment context. https://docs.python.org/3/library/ast.html - currently only `Name` and `Tuple` appear implemented. Might be worth splitting out a util function to validate those types and using in all assignment contexts - like a for loop (where I'm seeing the issue), a with, etc.

**Comment by arnimarj** [comment]
Hi. Found another test-case:

```
class hello(object):
	def cool(self):
		for [self.x, self.y, self.z] in [(1, 2, 3), (4, 5, 6)]:
			pass
```

**Comment by gforcada** [comment]
I just released version 1.4.0, give it a try and re-open if the errors still show up.

Again, thanks for using flake8-builtins and taking the time to report the issues you find with it!
